# Generated by Django 2.2.28 on 2023-08-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_azul'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMo45',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfd', models.BigIntegerField()),
            ],
        ),
    ]
