# Generated by Django 2.2.28 on 2023-08-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newmo45'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asa', models.BigIntegerField()),
            ],
        ),
    ]
